// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1rOtlMRD_TjkwJongO5RW9N2ZJRHGwU4',
    appId: '1:888823876979:web:46df29fb86a9df2796c906',
    messagingSenderId: '888823876979',
    projectId: 'skilful-reserve-363512',
    authDomain: 'skilful-reserve-363512.firebaseapp.com',
    storageBucket: 'skilful-reserve-363512.appspot.com',
    measurementId: 'G-E1156JH87V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwSGgXRtelz6SAt9-eVWt4-ByCt1OdxEI',
    appId: '1:888823876979:android:bde3264e00ea9cda96c906',
    messagingSenderId: '888823876979',
    projectId: 'skilful-reserve-363512',
    storageBucket: 'skilful-reserve-363512.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAnKUf-SXE_HDovmIT2SKZ1sYpERAWOrM',
    appId: '1:888823876979:ios:3fbb17d6ef29d68996c906',
    messagingSenderId: '888823876979',
    projectId: 'skilful-reserve-363512',
    storageBucket: 'skilful-reserve-363512.appspot.com',
    iosBundleId: 'com.example.elearningappDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAnKUf-SXE_HDovmIT2SKZ1sYpERAWOrM',
    appId: '1:888823876979:ios:9e8c1cc3f0354f8c96c906',
    messagingSenderId: '888823876979',
    projectId: 'skilful-reserve-363512',
    storageBucket: 'skilful-reserve-363512.appspot.com',
    iosBundleId: 'com.example.elearningappDemo.RunnerTests',
  );
}
